// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_body.proto

package com.ragentek.ypush.service.vo;

public final class commonMessage {
  private commonMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class commonMsg extends
      com.google.protobuf.GeneratedMessage {
    // Use commonMsg.newBuilder() to construct.
    private commonMsg() {
      initFields();
    }
    private commonMsg(boolean noInit) {}
    
    private static final commonMsg defaultInstance;
    public static commonMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public commonMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ragentek.ypush.service.vo.commonMessage.internal_static_vo_commonMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ragentek.ypush.service.vo.commonMessage.internal_static_vo_commonMsg_fieldAccessorTable;
    }
    
    // required string commText = 1;
    public static final int COMMTEXT_FIELD_NUMBER = 1;
    private boolean hasCommText;
    private java.lang.String commText_ = "";
    public boolean hasCommText() { return hasCommText; }
    public java.lang.String getCommText() { return commText_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasCommText) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasCommText()) {
        output.writeString(1, getCommText());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCommText()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getCommText());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.ragentek.ypush.service.vo.commonMessage.commonMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ragentek.ypush.service.vo.commonMessage.commonMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ragentek.ypush.service.vo.commonMessage.commonMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ragentek.ypush.service.vo.commonMessage.commonMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ragentek.ypush.service.vo.commonMessage.commonMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ragentek.ypush.service.vo.commonMessage.commonMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ragentek.ypush.service.vo.commonMessage.commonMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ragentek.ypush.service.vo.commonMessage.commonMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ragentek.ypush.service.vo.commonMessage.commonMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ragentek.ypush.service.vo.commonMessage.commonMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ragentek.ypush.service.vo.commonMessage.commonMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.ragentek.ypush.service.vo.commonMessage.commonMsg result;
      
      // Construct using com.ragentek.ypush.service.vo.commonMessage.commonMsg.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.ragentek.ypush.service.vo.commonMessage.commonMsg();
        return builder;
      }
      
      protected com.ragentek.ypush.service.vo.commonMessage.commonMsg internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.ragentek.ypush.service.vo.commonMessage.commonMsg();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ragentek.ypush.service.vo.commonMessage.commonMsg.getDescriptor();
      }
      
      public com.ragentek.ypush.service.vo.commonMessage.commonMsg getDefaultInstanceForType() {
        return com.ragentek.ypush.service.vo.commonMessage.commonMsg.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      
      public com.ragentek.ypush.service.vo.commonMessage.commonMsg build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.ragentek.ypush.service.vo.commonMessage.commonMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.ragentek.ypush.service.vo.commonMessage.commonMsg buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.ragentek.ypush.service.vo.commonMessage.commonMsg returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ragentek.ypush.service.vo.commonMessage.commonMsg) {
          return mergeFrom((com.ragentek.ypush.service.vo.commonMessage.commonMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ragentek.ypush.service.vo.commonMessage.commonMsg other) {
        if (other == com.ragentek.ypush.service.vo.commonMessage.commonMsg.getDefaultInstance()) return this;
        if (other.hasCommText()) {
          setCommText(other.getCommText());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setCommText(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string commText = 1;
      public boolean hasCommText() {
        return result.hasCommText();
      }
      
      public java.lang.String getCommText() {
        return result.getCommText();
      }
      
      public Builder setCommText(java.lang.String value) {
	        if (value == null) {
	        	throw new NullPointerException();
		    }
	    result.hasCommText = true;
        result.commText_ = value;
        return this;
      }
      
      public Builder clearCommText() {
        result.hasCommText = false;
        result.commText_ = getDefaultInstance().getCommText();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:vo.commonMsg)
    }
    
    static {
      defaultInstance = new commonMsg(true);
      com.ragentek.ypush.service.vo.commonMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:vo.commonMsg)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_vo_commonMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vo_commonMsg_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016msg_body.proto\022\002vo\"\035\n\tcommonMsg\022\020\n\010com" +
      "mText\030\001 \002(\tB.\n\035com.ragentek.ypush.servic" +
      "e.voB\rcommonMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_vo_commonMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_vo_commonMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_vo_commonMsg_descriptor,
              new java.lang.String[] { "CommText", },
              com.ragentek.ypush.service.vo.commonMessage.commonMsg.class,
              com.ragentek.ypush.service.vo.commonMessage.commonMsg.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
