// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heart_beat_packet.proto

package com.ragentek.ypush.service.vo;

public final class hbpMessage {
  private hbpMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class hbpMsg extends
      com.google.protobuf.GeneratedMessage {
    // Use hbpMsg.newBuilder() to construct.
    private hbpMsg() {
      initFields();
    }
    private hbpMsg(boolean noInit) {}
    
    private static final hbpMsg defaultInstance;
    public static hbpMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public hbpMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ragentek.ypush.service.vo.hbpMessage.internal_static_vo_hbpMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ragentek.ypush.service.vo.hbpMessage.internal_static_vo_hbpMsg_fieldAccessorTable;
    }
    
    // required string deviceId = 1;
    public static final int DEVICEID_FIELD_NUMBER = 1;
    private boolean hasDeviceId;
    private java.lang.String deviceId_ = "";
    public boolean hasDeviceId() { return hasDeviceId; }
    public java.lang.String getDeviceId() { return deviceId_; }
    
    // required string netType = 2;
    public static final int NETTYPE_FIELD_NUMBER = 2;
    private boolean hasNetType;
    private java.lang.String netType_ = "";
    public boolean hasNetType() { return hasNetType; }
    public java.lang.String getNetType() { return netType_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasDeviceId) return false;
      if (!hasNetType) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasDeviceId()) {
        output.writeString(1, getDeviceId());
      }
      if (hasNetType()) {
        output.writeString(2, getNetType());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasDeviceId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getDeviceId());
      }
      if (hasNetType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getNetType());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.ragentek.ypush.service.vo.hbpMessage.hbpMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ragentek.ypush.service.vo.hbpMessage.hbpMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ragentek.ypush.service.vo.hbpMessage.hbpMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ragentek.ypush.service.vo.hbpMessage.hbpMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ragentek.ypush.service.vo.hbpMessage.hbpMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ragentek.ypush.service.vo.hbpMessage.hbpMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ragentek.ypush.service.vo.hbpMessage.hbpMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ragentek.ypush.service.vo.hbpMessage.hbpMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ragentek.ypush.service.vo.hbpMessage.hbpMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ragentek.ypush.service.vo.hbpMessage.hbpMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ragentek.ypush.service.vo.hbpMessage.hbpMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.ragentek.ypush.service.vo.hbpMessage.hbpMsg result;
      
      // Construct using com.ragentek.ypush.service.vo.hbpMessage.hbpMsg.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.ragentek.ypush.service.vo.hbpMessage.hbpMsg();
        return builder;
      }
      
      protected com.ragentek.ypush.service.vo.hbpMessage.hbpMsg internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.ragentek.ypush.service.vo.hbpMessage.hbpMsg();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ragentek.ypush.service.vo.hbpMessage.hbpMsg.getDescriptor();
      }
      
      public com.ragentek.ypush.service.vo.hbpMessage.hbpMsg getDefaultInstanceForType() {
        return com.ragentek.ypush.service.vo.hbpMessage.hbpMsg.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.ragentek.ypush.service.vo.hbpMessage.hbpMsg build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.ragentek.ypush.service.vo.hbpMessage.hbpMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.ragentek.ypush.service.vo.hbpMessage.hbpMsg buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.ragentek.ypush.service.vo.hbpMessage.hbpMsg returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ragentek.ypush.service.vo.hbpMessage.hbpMsg) {
          return mergeFrom((com.ragentek.ypush.service.vo.hbpMessage.hbpMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ragentek.ypush.service.vo.hbpMessage.hbpMsg other) {
        if (other == com.ragentek.ypush.service.vo.hbpMessage.hbpMsg.getDefaultInstance()) return this;
        if (other.hasDeviceId()) {
          setDeviceId(other.getDeviceId());
        }
        if (other.hasNetType()) {
          setNetType(other.getNetType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setDeviceId(input.readString());
              break;
            }
            case 18: {
              setNetType(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string deviceId = 1;
      public boolean hasDeviceId() {
        return result.hasDeviceId();
      }
      public java.lang.String getDeviceId() {
        return result.getDeviceId();
      }
      public Builder setDeviceId(java.lang.String value) {
        if (value == null) {
		    throw new NullPointerException();
		}
        result.hasDeviceId = true;
        result.deviceId_ = value;
        return this;
      }
      public Builder clearDeviceId() {
        result.hasDeviceId = false;
        result.deviceId_ = getDefaultInstance().getDeviceId();
        return this;
      }
      
      // required string netType = 2;
      public boolean hasNetType() {
        return result.hasNetType();
      }
      public java.lang.String getNetType() {
        return result.getNetType();
      }
      public Builder setNetType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasNetType = true;
        result.netType_ = value;
        return this;
      }
      public Builder clearNetType() {
        result.hasNetType = false;
        result.netType_ = getDefaultInstance().getNetType();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:vo.hbpMsg)
    }
    
    static {
      defaultInstance = new hbpMsg(true);
      com.ragentek.ypush.service.vo.hbpMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:vo.hbpMsg)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_vo_hbpMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vo_hbpMsg_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027heart_beat_packet.proto\022\002vo\"+\n\006hbpMsg\022" +
      "\020\n\010deviceId\030\001 \002(\t\022\017\n\007netType\030\002 \002(\tB+\n\035co" +
      "m.ragentek.ypush.service.voB\nhbpMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_vo_hbpMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_vo_hbpMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_vo_hbpMsg_descriptor,
              new java.lang.String[] { "DeviceId", "NetType", },
              com.ragentek.ypush.service.vo.hbpMessage.hbpMsg.class,
              com.ragentek.ypush.service.vo.hbpMessage.hbpMsg.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
